#Constants
END=0
RUNNING=1
PAUSE=2
SCREEN_WIDTH=800
SCREEN_HEIGHT=600
TILE_WIDTH=50
TILE_HEIGHT=50
FRAME_RATE=30
GRAVITY=5
MAP_SIZE=(int(SCREEN_WIDTH/TILE_WIDTH), int(SCREEN_HEIGHT/TILE_HEIGHT))
TAGS=["Wall"]